#!/bin/bash

folder=`dirname $1`
echo ${folder}
filename=$1
extension="${filename##*.}"
filename="${filename%.*}"

# echo ${filename}
# echo ${extension}

xelatex --shell-escape -interaction nonstopmode -no-pdf -output-directory=${folder} ${filename}.tex && dvisvgm ${filename}.xdv -n -c 1.7 -o ${filename}.svg
